### ISSUE TITLE
IForgeBlock usage tracking - to be implemented later

### ISSUE THREAD

**Issue by coderbot16** [PatchworkMC/patchwork-api#20]
* [ ] [AceCraft](https://www.curseforge.com/minecraft/mc-mods/acecraft)
  * [ ] `getExpDrop`
  * [ ] `getHarvestLevel`
  * [ ] `isFullCube`

**Comment by rikka0w0** [comment]
* [ ] [SimElectricity](https://www.curseforge.com/minecraft/mc-mods/simelectricity)
 * [ ] `hasTileEntity`
 * [ ] `createTileEntity`
 * [ ] `removedByPlayer` Return false to cancel the block removal
 * [ ] isAir

**Comment by TheGlitch76** [comment]
Closing because we have moved to 1.16
